pages:
  - text_size: 10
    fields:
      - name: amount
        location:
          left: 58
          top: 629
          width: 130
      - name: date
        location:
          - left: 253
            top: 629
            width: 130
          - left: 410
            top: 629
            width: 130
          - left: 280
            top: 285
            width: 130
      - name: full_name
        location:
          left: 82
          top: 604
          width: 400
      - name: postal_address
        location:
          left: 60
          top: 580
          width: 400
      - name: city
        location:
          left: 42
          top: 554.5
          width: 100
      - name: country
        location:
          left: 177
          top: 554.5
          width: 100
      - name: zip_code
        location:
          left: 323
          top: 554.5
          width: 75
      - name: phone_number
        location:
          left: 423
          top: 554.5
          width: 100
      - name: label
        location:
          left: 475
          top: 466
          width: 50
  - text_size: 5
    upcase: true
    fields:
      - name: full_name
        location:
          - left: 115
            top: 530
            width: 240
          - left: 115
            top: 319
            width: 120
      - name: postal_address
        location:
          left: 115
          top: 468.5
          width: 230
          line_space: 11.5
      - name: city
        location:
          left: 252
          top: 433.5
          width: 100
      - name: country
        location:
          left: 115
          top: 416.5
          width: 100
      - name: zip_code
        location:
          left: 115
          top: 433.5
          width: 75
      - name: phone_number
        location:
          left: 115
          top: 382
          width: 120
      - name: email
        location:
          left: 310
          top: 320
          width: 130
          upcase: false
      - name: bank_name
        location:
          left: 115
          top: 248
          width: 145
          line_space: 3
      - name: bank_postal_address
        location:
          left: 115
          top: 239.5
          width: 117
          line_space: 3
      - name: bank_country
        location:
          left: 115
          top: 221.5
          width: 140
      - name: bank_holder
        location:
          left: 177
          top: 196
          width: 110
      - name: bank_national_account
        location:
          left: 310
          top: 231
          width: 100
      - name: bank_bic
        location:
          left: 310
          top: 205
          width: 100
      - name: bank_iban
        location:
          left: 310
          top: 188
          width: 100
      - name: bank_national_code
        location:
          - left: 310
            top: 248.5
            width: 100
          - left: 310
            top: 170
            width: 100
