common: &common
  program_name: "Demo Travel Support Program"

  days_for_reminder: 3
  async_emails: true
  email_from: "Travel Support Program <noreply@example.com>"
  email_footer: "Travel Support Program"
  email_default_url_options:
    host: 'localhost:3000'

  # theme: "bento"

  authentication:
    ichain:
      enabled: false
      base_url: ""
    database:
      enabled: true

  opensuse_connect:
    enabled: true
    api_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    base_url: "https://connect.opensuse.org"

  external_links:
    - title: "openSUSE TSP"
      url: "http://opensuse.org/openSUSE:Travel_Support_Program"
    - title: "Application's Github"
      url: "https://github.com/openSUSE/travel-support-program"
  request_expense_subjects:
    - Plane
    - Train
    - Bus
    - Lodging
    - Other
  currencies_for_approved:
    - EUR
    - USD
  payment_methods:
    - Transfer
    - Check

production:
  <<: *common

development:
  <<: *common

test:
  <<: *common
  async_emails: false
  request_expense_subjects:
    - Gas
    - Droid rental
    - Lodging
    - Other
