common: &common
  email_from: "Travel Support Program <noreply@example.com>"
  email_footer: "Travel Support Program"
  email_base_url: "http://localhost:3000/"

production:
  <<: *common

development:
  <<: *common

test:
  <<: *common

