common: &common
  email_from: "Travel Support Program <noreply@example.com>"
  email_footer: "Travel Support Program"
  email_base_url: "http://localhost:3000/"
  async_emails: true
  request_expense_subjects:
    - Plane
    - Train
    - Bus
    - Lodging
    - Other

production:
  <<: *common

development:
  <<: *common

test:
  <<: *common
  request_expense_subjects:
    - Gas
    - Droid rental
    - Lodging
    - Other
