common: &common
  async_emails: true
  email_from: "Travel Support Program <noreply@example.com>"
  email_footer: "Travel Support Program"
  email_default_url_options:
    host: 'localhost:3000'

  # theme: "bento"
  # Currently, when enabling opensuse_auth_proxy, the usage of bento theme is
  # mandatory as long as there are some issues combining the openSUSE
  # authentication proxy and the default theme. These issues will be solved as
  # soon as possible.
  opensuse_auth_proxy:
    enabled: false
    proxy_base_url: "https://connect.opensuse.org"
    connect:
      api_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      base_url: "https://connect.opensuse.org"

  external_links:
    - title: "openSUSE TSP"
      url: "http://opensuse.org/openSUSE:Travel_Support_Program"
    - title: "Application's Github"
      url: "https://github.com/openSUSE/travel-support-program"
  request_expense_subjects:
    - Plane
    - Train
    - Bus
    - Lodging
    - Other
  currencies_for_approved:
    - EUR
    - USD

production:
  <<: *common

development:
  <<: *common

test:
  <<: *common
  async_emails: false
  request_expense_subjects:
    - Gas
    - Droid rental
    - Lodging
    - Other
